name: CI-CD Flip Mobile
run-name: ${{ github.ref_name == 'master' && 'Deploy to TestFlight' || 'Run Unit Test'  }} | on ${{ github.ref_name }} branch | by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      isRelease:
        type: boolean
        description: is Release to TestFlight

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run SwiftLint
        run: echo SwiftLint running...
      - name: Carthage Update
        continue-on-error: true
        run: carthage update --platform iOS --no-use-binaries --use-xcframeworks
      - name: Run Script Build Carthage
        run: bash carthage-build.sh build --platform iOS --use-xcframeworks
      - name: Build
        run: xcodebuild clean build -workspace Flip.xcworkspace -scheme "FlipMobile Debug" -destination "${destination}" CODE_SIGN_IDENTITY="" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
        env:
          destination: ${{ matrix.destination }}
      - name: Test
        run: xcodebuild \
            -target "FlipMobile Debug" \
            -sdk iphonesimulator \
            -destination "${destination}" \
            test
        # run: xcodebuild clean test -workspace Flip.xcworkspace -scheme "FlipMobile Debug" -destination "${destination}" CODE_SIGN_IDENTITY="" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
        env:
          destination: ${{ matrix.destination }}
      - name: Archive
        if: ${{ github.ref_name == 'master' && inputs.isRelease }}
        run: echo ${{ inputs.isRelease }}
